import { createContext, useContext, useState } from 'react'

/* ── Language metadata ────────────────────────────────────────────────────── */
export const LANG_META = {
  he: { name: 'עברית',     flag: '🇮🇱', rtl: true,  locale: 'he-IL' },
  en: { name: 'English',   flag: '🇺🇸', rtl: false, locale: 'en-US' },
  ar: { name: 'العربية',   flag: '🇸🇦', rtl: true,  locale: 'ar-SA' },
  ru: { name: 'Русский',   flag: '🇷🇺', rtl: false, locale: 'ru-RU' },
  es: { name: 'Español',   flag: '🇪🇸', rtl: false, locale: 'es-ES' },
  fr: { name: 'Français',  flag: '🇫🇷', rtl: false, locale: 'fr-FR' },
  de: { name: 'Deutsch',   flag: '🇩🇪', rtl: false, locale: 'de-DE' },
  pt: { name: 'Português', flag: '🇧🇷', rtl: false, locale: 'pt-BR' },
  am: { name: 'አማርኛ',    flag: '🇪🇹', rtl: false, locale: 'am-ET' },
}

/* ── Full translations ────────────────────────────────────────────────────── */
const T = {

  /* ════════════════════════════ ENGLISH (base) ════════════════════════════ */
  en: {
    /* Nav */
    home: 'Home', devices: 'Devices', automations: 'Auto',
    security: 'Security', rooms: 'Rooms', network: 'Network',
    history: 'History', settings: 'Settings',

    /* General */
    save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit',
    add: 'Add', close: 'Close', search: 'Search', loading: 'Loading...',
    save_changes: 'Save Changes', create: 'Create', confirm: 'Confirm',
    yes: 'Yes', no: 'No', back: 'Back', next: 'Next',
    error: 'Error', unknown_error: 'Unknown error',
    no_results: 'No results found', all: 'All',
    optional: 'Optional', required: 'Required',

    /* Status */
    connected: 'Connected', connecting: 'Connecting...', disconnected: 'Disconnected',
    online: 'Online', offline: 'Offline', active: 'Active', inactive: 'Inactive',

    /* Dashboard */
    devices_count: 'Devices', connected_count: 'Online',
    rooms_count: 'Rooms', automations_count: 'Automations',
    pinned_devices: '📌 Pinned', active_now: '⚡ Active Now',
    turn_all_off: 'Turn All Off', no_active_devices: 'No active devices',
    go_to_devices: 'Go to Devices',
    recent_activity: 'Recent Activity', see_all: 'All ›',
    turned_on: 'Turned on', turned_off: 'Turned off', command_sent: 'Command',
    hub_not_connected: 'Hub Not Connected',
    hub_banner_hint: 'Make sure start-hub.bat is running as Administrator, and both PC and phone are on the same WiFi network.',
    hub_settings: '⚙️ Hub Settings', network_diag: '🔧 Network Diagnostics',
    recommended_products: '🛒 Recommended Smart Home Products',
    show_recommendations: '🛒 Show Recommendations',
    show_all: 'Show All', show_less: 'Show Less',
    buy_now: 'Buy Now ›',

    /* History */
    history_title: 'History', clear: 'Clear',
    confirm_clear_history: 'Delete all history?',
    no_history: 'No records',
    search_history: '🔍 Search device or action...',

    /* Rooms */
    rooms_title: 'Rooms', new_room: '+ New Room',
    no_rooms: 'No rooms — click "New Room"',
    room_name_label: 'Room Name', room_icon_label: 'Icon',
    edit_room: '✏️ Edit Room', create_room: '🏠 New Room',
    room_name_placeholder: 'Living room, Kitchen, Bedroom...',
    room_name_required: 'Room name cannot be empty',
    room_hub_error: 'Error: Hub not found — restart start-hub.bat',
    confirm_delete_room: 'Devices in this room will be moved to "No Room".',
    save_room: '✅ Create Room', edit_room_save: '💾 Save Changes',
    edit_name: '✏️ Rename', delete_room: '🗑️ Delete Room',
    saving: 'Saving...', no_room: 'No Room',

    /* Security */
    security_title: 'Security', alarm_system: 'Alarm Status',
    disarmed: 'Disarmed', home_mode: 'Home', armed: 'Armed', night_mode: 'Night',
    arming_in: 'Arming in', seconds_abbr: 's',
    cancel_arm: 'Cancel', active_alerts: 'Active Alerts',
    security_devices: 'Security Devices', connected_devices: 'Online',
    alerts_count: 'Alerts',
    locks_section: 'Locks', motion_sensors: 'Motion Sensors',
    door_sensors: 'Door / Window Sensors', smoke_detectors: 'Smoke Detectors',
    cameras_section: 'Cameras',
    security_history_title: 'Recent Security Events',
    no_security_devices: 'No Security Devices',
    no_security_hint: 'Add devices of type lock, motion sensor, smoke detector, door sensor or camera in the Devices page',
    no_recent_events: 'No recent security events',
    lock_btn: 'Lock', unlock_btn: 'Unlock',
    motion_detected_badge: '👤 Detected', quiet_badge: '○ Clear',
    door_open_badge: '🚪 Open', door_closed_badge: '✅ Closed',
    smoke_alert_badge: '🔥 Smoke!', smoke_ok_badge: '✅ OK',
    smoke_alert_banner: '🔥 Smoke Detected!',
    motion_alert_banner: '👤 Motion Detected',
    door_open_banner: '🚪 Open',
    offline_badge: '● Offline',
    view_stream: '▶ View Stream',

    /* Devices */
    add_device: 'Add Device', scan_qr: 'Scan QR Code',
    scan_network: 'Scan Network', manual_add: 'Add Manually',
    import_app: 'Import from App',
    no_devices: 'No devices — click Add',
    pin: 'Pin', unpin: 'Unpin',
    pinned: '📌 Pinned', pin_btn: '📌 Pin',
    rename_btn: '✏️ Edit', delete_btn: '🗑️ Delete',
    device_unique_id: 'Unique ID', device_name: 'Name',
    device_label: 'Brand / Label (optional)',
    device_protocol: 'Protocol', device_type: 'Type',
    device_room: 'Room', new_device: 'New Device ✏️',
    fill_id_name: 'Please fill ID and Name',
    edit_device_title: 'Edit Device',
    confirm_delete_device: 'Delete',
    add_ac: 'Add A/C', moes_gateway: 'Moes Gateway',
    scan_qr_btn: 'Scan QR', scan_network_btn: 'Scan Network',
    manual_btn: 'Manual', import_json: 'Import JSON',
    ac_sub: 'Sensibo / MQTT / Tuya',
    moes_sub: 'Zigbee / BLE / Tuya',
    qr_sub: 'Device QR code',
    network_sub: 'Search local network',
    manual_sub: 'Configure manually',
    import_sub: 'Load backup file',
    pinned_section: '📌 Pinned',
    all_devices_section: 'All Devices',

    /* DeviceCard */
    brightness: 'Brightness', color: 'Color', warm_cold: 'Warm ↔ Cool',
    battery: 'Battery',

    /* Network */
    scan_wifi: 'Scan WiFi Networks', connect: 'Connect',
    auto_connect: 'Auto Connect', saved_networks: 'Saved Networks',
    enter_password: 'Enter password', save_connection: 'Save Connection',
    scanning: 'Scanning...', rescan: 'Scan Again',
    current_network: 'Current Network', available_networks: 'Available Networks',
    no_networks: 'No networks found',
    connect_btn: 'Connect', connecting_to: 'Connecting to',
    connected_to: 'Connected to', connection_failed: 'Connection Failed',
    wrong_password: 'Wrong password', not_found: 'Network not found',
    network_title: 'Network & Connections',

    /* Automations */
    rules_title: 'Automations', add_rule: '+ New', no_rules: 'No Automations',
    no_rules_hint: 'Create an automation to control devices by time, sensor state, and more',
    create_first_rule: '+ Create First Automation',
    rules_count: 'rules',
    rule_name: 'Automation Name', trigger: 'If... (Trigger)', actions_label: 'Then... (Actions)',
    enable_rule: 'Enable', disable_rule: 'Disable', delete_rule: 'Delete',
    save_rule: '⚡ Create Automation', edit_rule: '💾 Save Changes', new_rule: '⚡ New Automation',
    edit_rule_title: '✏️ Edit Automation',
    trigger_type: 'Trigger Type', device: 'Device', condition: 'Condition', value: 'Value',
    action_type: 'Action Type', add_action: '+ Add Action', remove_action: 'Remove',
    fill_rule_name: 'Fill in automation name', add_min_one_action: 'Add at least one action',
    rule_enabled: 'Automation active', rule_disabled: 'Automation disabled',
    last_fired: 'Last fired',
    rule_if: 'If ', rule_then: 'Then ',

    /* Settings */
    language: 'Language', api_keys: 'API Keys',
    import_export: 'Import / Export', export_devices: 'Export Devices',
    import_devices: 'Import Devices', import_ha: 'Import from Home Assistant',
    ha_url: 'Home Assistant URL', ha_token: 'HA Token',
    about: 'About', version: 'Version',

    /* Scenes */
    scenes_title: 'Scenes', new_scene: '+ New Scene',
    no_scenes: 'No Scenes',
    no_scenes_hint: 'Create a scene to control multiple devices with one tap',
    create_first_scene: '+ Create First Scene',
    scenes_hint: 'Scene = a group of actions triggered with one tap',

    /* AI */
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'Not configured — set API key in Settings',
    type_message: 'Ask me something...',

    /* Settings descriptions */
    sponsored: 'Sponsored',
    show_ads: '📢 Show Ads',
    gemini_section_title: 'Gemini AI — Smart Home Assistant',
    gemini_hint: 'Gemini lets you control your home by chat: "Turn off living room lights", "Set AC to 22°"',
    gemini_api_hint: 'Get a free API key at aistudio.google.com → Get API Key',
    gemini_after_save: 'After saving — go to Devices → + Add → ❄️ Add AC → Import from Sensibo',
    sensibo_section_title: 'Sensibo — Smart A/C',
    sensibo_hint: 'Sensibo connects any AC brand to the network. Get API key at home.sensibo.com',

    /* Cameras */
    cameras_title: 'Cameras',
    add_camera: '+ Add Camera',
    no_cameras: 'No cameras added',
    no_cameras_hint: 'Add a device of type "camera" in the Devices page, or tap + Add Camera',
    camera_stream_url: 'Stream URL',
    camera_stream_placeholder: 'http://192.168.1.x/video.mjpg',
    camera_snapshot_url: 'Snapshot URL (optional)',
    camera_name: 'Camera Name',
    camera_refresh: 'Refresh',
    camera_fullscreen: 'Full Screen',
    camera_live: '● Live',
    camera_stream_type: 'Stream Type',
    camera_type_mjpeg: 'MJPEG Stream',
    camera_type_snapshot: 'Snapshot (auto-refresh)',
    camera_type_hls: 'HLS / MP4',
    camera_type_iframe: 'Web Embed',
    camera_edit_title: 'Edit Camera',
    camera_add_title: 'Add Camera',
    gemini_hint_smart: 'Ask me anything — "turn off living room lights"',

    /* QR */
    qr_scanning: 'Scanning... point camera at QR code',
    qr_not_available: 'Camera not available in browser',

    /* HubSetup */
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'Connect to your home server',
    prev_url_warning: 'Could not connect to:',
    phone_ip_hint: 'Phone IP:',
    phone_subnet_hint: '— Hub should be on',
    discover_auto: '🔍 Auto-Discover Hub',
    enter_ip_manual: '✏️ Enter IP Manually',
    hub_not_found_title: 'Hub Not Found — check the following:',
    hub_searching: 'Searching for Hub on network...', hub_found: '✅ Hub Found!',
    stop: 'Stop',
    hub_ip_label: 'Enter Hub Address',
    hub_ip_desc: 'The address is shown in the start-hub.bat window:',
    connect_btn2: '🔗 Connect',
    cannot_connect_error: 'Cannot connect to',
    check_hub_running: 'Make sure Hub is running (start-hub.bat as Admin) and the address is correct.',
    instructions_title: '📋 Setup Instructions',
    instr1: 'Open smarthome-hub\\hub folder on PC',
    instr2: 'Right-click start-hub.bat → Run as Administrator',
    instr3: 'Make sure PC + phone are on the same WiFi',
    instr4: 'Click "Auto-Discover Hub" ↑',
    checklist_bat: 'Is start-hub.bat running as Admin?',
    checklist_bat_detail: 'Right-click start-hub.bat → "Run as Administrator". A black window should stay open showing the IP address.',
    checklist_wifi: 'PC + Phone on same WiFi?',
    checklist_wifi_detail: 'Make sure both are connected to the same router. Network names (SSID) should be identical, or at least on the same home network.',
    checklist_firewall: 'Windows Firewall blocking?',
    checklist_firewall_detail: 'When Python first ran, you may have clicked "Block". Open:\nWindows Search → "Windows Defender Firewall" → "Allow an App" → find Python → check all → OK.',
    checklist_isolation: 'AP Isolation enabled on router?',
    checklist_isolation_detail: 'Open router interface (192.168.1.1)\nFind: Wireless Settings → AP Isolation → Disable',
    checklist_ethernet: 'Try Ethernet cable?',
    checklist_ethernet_detail: 'Connect PC directly to router with a network cable.',

    /* ── Device types ── */
    dev_type_switch: 'Switch / Socket', dev_type_light: 'Light',
    dev_type_dimmer: 'Dimmer',         dev_type_sensor: 'Sensor',
    dev_type_fan: 'Fan',               dev_type_lock: 'Lock',
    dev_type_camera: 'Camera',         dev_type_ac: 'Air Conditioner',
    unknown_type: 'Unknown',

    /* ── Network / DeviceScanner ── */
    net_scan_btn: '🔍 Scan Network Devices',
    net_identifying: 'Identifying devices...',
    net_hint_arp: 'Checking ARP table...',
    net_hint_ping: 'Pinging network (up to 25s)...',
    net_hint_tasmota: 'Searching Tasmota / Shelly...',
    net_hint_upnp: 'Scanning UPnP / mDNS...',
    net_hint_almost: 'Almost done...',
    net_no_devices_found: 'No devices found. Make sure you are on the same WiFi network.',
    net_scan_failed: 'Scan failed — make sure Hub is running',
    net_info_title: '🌐 Quick Network Info',
    net_hub_ip: 'Hub Address', net_gateway: 'Default Gateway',
    net_subnet: 'Network', net_arp_count: 'ARP Devices',
    net_found: 'Found', net_devices_word: 'devices',
    net_auto_pairable: 'auto-pairable',
    net_auto_pair: '⚡ Auto Pair',
    net_manual_add_section: '🔧 Manual Add',
    net_paired_section: '✅ Paired',
    net_mqtt_auto: '⚡ MQTT settings will be configured automatically on the device',
    net_room_area: 'Room / Area',
    net_pairing: 'Pairing...',
    net_pair_auto_btn: '⚡ Auto Pair',
    net_add_device_btn: '+ Add Device',
    net_paired_tag: '✓ Paired',
    net_auto_tag: '⚡ Auto',
    net_pair_btn: '⚡ Pair',
    net_pair_error: 'Pairing error',
    net_paired_ok: 'paired and added to system',
    net_tab_wifi: '📶 Network',

    /* ── Bluetooth ── */
    bt_not_available: 'Bluetooth is not available in browser',
    bt_install_apk: 'Install the APK on Android to use Bluetooth scanning',
    bt_initializing: '⏳ Initializing...',
    bt_stop_scan: '⏹ Stop Scan',
    bt_scan_btn: '🔵 Scan Bluetooth Devices',
    bt_scanning: 'Searching for BLE devices nearby...',
    bt_empty_hint: 'Press Scan to search for nearby Bluetooth devices',
    bt_added_tag: '✓ Added',
    bt_add_to_system: '+ Add to System',
    bt_scan_error: 'Scan failed:',
    bt_save_error: 'Error saving',
    bt_added_ok: 'added to system',

    /* ── Zigbee ── */
    z2m_active_label: 'Zigbee2MQTT ● Active (MQTT)',
    z2m_devices_connected: 'devices connected',
    z2m_scan_btn: '🔶 Search Zigbee Bridges',
    z2m_no_bridges: 'No Zigbee bridges found. Make sure device is on the same network.',
    z2m_found_bridges_word: 'bridges found',
    z2m_verified: '✓ Verified', z2m_unverified: '❓ Unverified',
    z2m_devices_btn: '📋 Devices',
    z2m_loading_devices: '⏳ Loading devices...',
    z2m_load_error: 'Error loading devices',
    z2m_no_devices_hint: 'No devices — make sure Zigbee2MQTT is running and connected to MQTT',
    z2m_imported_tag: '✓ Imported',
    z2m_unsupported: 'Not Supported',
    z2m_not_completed: '❓ Incomplete',
    z2m_import_btn: '+ Import',
    z2m_mqtt_section: 'Devices from MQTT',
    z2m_load_btn: '📥 Load Devices from Zigbee2MQTT',
    z2m_import_error: 'Error importing',
    z2m_imported_ok: 'imported successfully',
    z2m_importing: '⏳ Importing...',
    z2m_import_to_system: '+ Import to System',

    /* ── Matter ── */
    matter_active: '● Active', matter_inactive: '○ Inactive',
    matter_nodes_count: 'devices paired',
    matter_server_required: 'python-matter-server required for pairing',
    how_btn: '❓ How?',
    matter_scan_btn: '🔍 Scan Matter Devices',
    matter_commission_btn: '🔷 Pair Device',
    matter_no_devices: 'No Matter devices found. Make sure device is in pairing mode.',
    matter_ready_to_pair: '📲 Ready to Pair',
    matter_already_paired: '✅ Already Paired',
    matter_pair_btn: '🔗 Pair',
    matter_system_nodes: '🔷 Matter Devices in System',
    matter_modal_title: '🔷 Pair Matter Device',
    matter_code_label: 'Pairing Code (QR / 11-digit number)',
    matter_commissioning: '⏳ Pairing...',
    matter_enter_code: 'Enter pairing code',
    matter_pair_failed: 'Pairing failed',
    matter_remove_confirm_prefix: 'Remove',
    matter_remove_error: 'Error removing',
    matter_paired_ok: 'paired successfully',
    matter_scanning: '⏳ Scanning...',

    /* ── WiFi ── */
    wifi_hub_connected_label: 'Hub connected · Signal',
    wifi_adapter_off: 'WiFi adapter is off or not available',
    wifi_scan_btn: '📡 Scan WiFi Networks',
    wifi_scanning_label: 'Scanning WiFi networks...',
    wifi_retrying: 'No networks found — retrying...',
    wifi_last_scan: 'Last updated:',
    wifi_networks_count: 'networks',
    wifi_manual_hint: 'No networks found — enter name manually:',
    wifi_ssid_placeholder: 'Network name (SSID)...',
    wifi_dual_band: '📶 Dual-Band detected',
    wifi_iot_24ghz: '— IoT devices (Tasmota/Shelly) only support 2.4GHz.',
    wifi_available_networks: '📡 Available Networks',
    wifi_24ghz_label: '✓ 2.4 GHz — suitable for smart home',
    wifi_5ghz_label: '⚡ 5 GHz — faster (not for IoT)',
    wifi_saved_routers_label: '💾 Saved Routers',
    wifi_priority_tag: '★ Priority',
    wifi_available_now: 'Available',
    wifi_not_in_scan: 'Not found in scan',
    wifi_secured: '🔒 Secured',
    wifi_open: 'Open',
    wifi_5ghz_warning: '⚠️ 5GHz — not suitable for IoT devices (Tasmota, Shelly).',
    wifi_password_label: 'WiFi Password',
    wifi_save_next: 'Save for next time',
    wifi_auto_on_start: 'Auto-connect on startup',
    wifi_connecting_btn: '⏳ Connecting...',
    wifi_connect_btn_label: '🔗 Connect',
    wifi_enter_password: 'Enter password',
    wifi_connected_ok: 'Connected successfully to',
    wifi_conn_failed: 'Connection failed — check password',
    wifi_remove_confirm: 'Delete from saved networks?',
    wifi_saved_tag: '💾 Saved',
    wifi_open_badge: '🔓 Open',
  },

  /* ═══════════════════════════════ HEBREW ════════════════════════════════ */
  he: {
    home: 'בית', devices: 'מכשירים', automations: 'אוטו',
    security: 'אבטחה', rooms: 'חדרים', network: 'רשת',
    history: 'היסטוריה', settings: 'הגדרות',
    save: 'שמור', cancel: 'ביטול', delete: 'מחק', edit: 'ערוך',
    add: 'הוסף', close: 'סגור', search: 'חיפוש', loading: 'טוען...',
    save_changes: 'שמור שינויים', create: 'צור', confirm: 'אשר',
    yes: 'כן', no: 'לא', back: 'חזור', next: 'הבא',
    error: 'שגיאה', unknown_error: 'שגיאה לא ידועה',
    no_results: 'לא נמצאו תוצאות', all: 'הכל',
    optional: 'אופציונלי', required: 'חובה',
    connected: 'מחובר', connecting: 'מתחבר...', disconnected: 'לא מחובר',
    online: 'מחובר', offline: 'לא מחובר', active: 'פעיל', inactive: 'לא פעיל',
    devices_count: 'מכשירים', connected_count: 'מחוברים',
    rooms_count: 'חדרים', automations_count: 'אוטומציות',
    pinned_devices: '📌 מוצמדים', active_now: '⚡ פועלים עכשיו',
    turn_all_off: 'כבה הכל', no_active_devices: 'אין מכשירים פעילים',
    go_to_devices: 'עבור למכשירים',
    recent_activity: 'פעולות אחרונות', see_all: 'הכל ›',
    turned_on: 'הודלק', turned_off: 'כובה', command_sent: 'פקודה',
    hub_not_connected: 'Hub לא מחובר',
    hub_banner_hint: 'ודא ש-start-hub.bat פועל כמנהל מערכת במחשב, ושהמחשב והטלפון על אותה רשת WiFi.',
    hub_settings: '⚙️ הגדרות Hub', network_diag: '🔧 אבחון רשת',
    recommended_products: '🛒 מוצרים מומלצים לבית החכם',
    show_recommendations: '🛒 הצג מוצרים מומלצים',
    show_all: 'הצג הכל', show_less: 'הצג פחות',
    buy_now: 'קנה עכשיו ›',
    history_title: 'היסטוריה', clear: 'נקה',
    confirm_clear_history: 'למחוק את כל ההיסטוריה?',
    no_history: 'אין רשומות',
    search_history: '🔍 חפש מכשיר או פעולה...',
    rooms_title: 'חדרים', new_room: '+ חדר חדש',
    no_rooms: 'אין חדרים — לחץ "חדר חדש"',
    room_name_label: 'שם החדר', room_icon_label: 'אייקון',
    edit_room: '✏️ עריכת חדר', create_room: '🏠 חדר חדש',
    room_name_placeholder: 'סלון, מטבח, חדר שינה...',
    room_name_required: 'שם החדר לא יכול להיות ריק',
    room_hub_error: 'שגיאה: ה-Hub לא מוצא את הנתיב — הפעל מחדש את start-hub.bat',
    confirm_delete_room: 'מכשירים בחדר זה יועברו ל"ללא חדר".',
    save_room: '✅ צור חדר', edit_room_save: '💾 שמור שינויים',
    edit_name: '✏️ ערוך שם', delete_room: '🗑️ מחק חדר',
    saving: 'שומר...', no_room: 'ללא חדר',
    security_title: 'אבטחה', alarm_system: 'מצב האזעקה',
    disarmed: 'כבוי', home_mode: 'בבית', armed: 'מופעל', night_mode: 'לילה',
    arming_in: 'מופעל בעוד', seconds_abbr: 'ש',
    cancel_arm: 'ביטול', active_alerts: 'התראות פעילות',
    security_devices: 'מכשירי אבטחה', connected_devices: 'מחוברים',
    alerts_count: 'התראות',
    locks_section: 'מנעולים', motion_sensors: 'חיישני תנועה',
    door_sensors: 'חיישני דלת/חלון', smoke_detectors: 'גלאי עשן',
    cameras_section: 'מצלמות',
    security_history_title: 'אירועי אבטחה אחרונים',
    no_security_devices: 'אין מכשירי אבטחה',
    no_security_hint: 'הוסף מכשירים מסוג מנעול, חיישן תנועה, גלאי עשן, חיישן דלת או מצלמה בדף המכשירים',
    no_recent_events: 'אין אירועי אבטחה אחרונים',
    lock_btn: 'נעל', unlock_btn: 'פתח',
    motion_detected_badge: '👤 זוהה', quiet_badge: '○ שקט',
    door_open_badge: '🚪 פתוח', door_closed_badge: '✅ סגור',
    smoke_alert_badge: '🔥 עשן!', smoke_ok_badge: '✅ תקין',
    smoke_alert_banner: '🔥 זוהה עשן!',
    motion_alert_banner: '👤 תנועה זוהתה',
    door_open_banner: '🚪 פתוח',
    offline_badge: '● לא מחובר',
    view_stream: '▶ צפה בשידור',
    add_device: 'הוסף מכשיר', scan_qr: 'סרוק קוד QR',
    scan_network: 'סרוק רשת', manual_add: 'הוסף ידנית',
    import_app: 'יבא מאפליקציה',
    no_devices: 'אין מכשירים — לחץ הוסף',
    pin: 'הצמד', unpin: 'בטל הצמדה',
    pinned: '📌 מוצמד', pin_btn: '📌 הצמד',
    rename_btn: '✏️ ערוך', delete_btn: '🗑️ מחק',
    device_unique_id: 'ID ייחודי', device_name: 'שם',
    device_label: 'ספק / תווית (אופציונלי)',
    device_protocol: 'פרוטוקול', device_type: 'סוג',
    device_room: 'חדר', new_device: 'מכשיר חדש ✏️',
    fill_id_name: 'מלא ID ושם',
    edit_device_title: 'עריכת מכשיר',
    confirm_delete_device: 'למחוק את',
    add_ac: 'הוסף מזגן', moes_gateway: 'Moes Gateway',
    scan_qr_btn: 'סרוק QR', scan_network_btn: 'סרוק רשת',
    manual_btn: 'ידנית', import_json: 'יבא JSON',
    ac_sub: 'Sensibo / MQTT / Tuya',
    moes_sub: 'Zigbee / BLE / Tuya',
    qr_sub: 'קוד QR של מכשיר',
    network_sub: 'חיפוש ברשת המקומית',
    manual_sub: 'הגדר מכשיר חדש',
    import_sub: 'טען קובץ גיבוי',
    pinned_section: '📌 מוצמדים',
    all_devices_section: 'שאר המכשירים',
    brightness: 'בהירות', color: 'צבע', warm_cold: 'חם ↔ קר',
    battery: 'סוללה',
    scan_wifi: 'סרוק רשתות WiFi', connect: 'התחבר',
    auto_connect: 'חיבור אוטומטי', saved_networks: 'רשתות שמורות',
    enter_password: 'הכנס סיסמה', save_connection: 'שמור חיבור',
    scanning: 'סורק...', rescan: 'סרוק שוב',
    current_network: 'רשת נוכחית', available_networks: 'רשתות זמינות',
    no_networks: 'לא נמצאו רשתות',
    connect_btn: 'התחבר', connecting_to: 'מתחבר ל',
    connected_to: 'מחובר ל', connection_failed: 'חיבור נכשל',
    wrong_password: 'סיסמה שגויה', not_found: 'רשת לא נמצאה',
    network_title: 'רשת וחיבורים',
    rules_title: 'אוטומציות', add_rule: '+ חדשה', no_rules: 'אין אוטומציות',
    no_rules_hint: 'צור אוטומציה כדי להפעיל מכשירים לפי זמן, מצב חיישן, ועוד',
    create_first_rule: '+ צור אוטומציה ראשונה',
    rules_count: 'כללים',
    rule_name: 'שם האוטומציה', trigger: 'אם... (טריגר)', actions_label: 'אז... (פעולות)',
    enable_rule: 'הפעל', disable_rule: 'כבה', delete_rule: 'מחק',
    save_rule: '⚡ צור אוטומציה', edit_rule: '💾 שמור שינויים', new_rule: '⚡ אוטומציה חדשה',
    edit_rule_title: '✏️ ערוך אוטומציה',
    trigger_type: 'סוג טריגר', device: 'מכשיר', condition: 'תנאי', value: 'ערך',
    action_type: 'סוג פעולה', add_action: '+ הוסף פעולה', remove_action: 'הסר',
    fill_rule_name: 'מלא שם לאוטומציה', add_min_one_action: 'הוסף לפחות פעולה אחת',
    rule_enabled: 'אוטומציה פעילה', rule_disabled: 'אוטומציה כבויה',
    last_fired: 'הופעל לאחרונה',
    rule_if: 'אם ', rule_then: 'אז ',
    language: 'שפה', api_keys: 'מפתחות API',
    import_export: 'יבוא / יצוא', export_devices: 'יצא מכשירים',
    import_devices: 'יבא מכשירים', import_ha: 'יבא מ-Home Assistant',
    ha_url: 'כתובת Home Assistant', ha_token: 'טוקן HA',
    about: 'אודות', version: 'גרסה',
    scenes_title: 'סצנות', new_scene: '+ סצנה חדשה',
    no_scenes: 'אין סצנות',
    no_scenes_hint: 'צור סצנה כדי להפעיל מספר מכשירים בלחיצה אחת',
    create_first_scene: '+ צור סצנה ראשונה',
    scenes_hint: 'סצנה = קבוצת פעולות שמופעלות בלחיצה אחת',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'לא מוגדר — הגדר מפתח API בהגדרות',
    type_message: 'שאל אותי משהו...',
    gemini_hint_smart: 'שאל אותי על הבית החכם — "כבה את אורות הסלון"',
    cameras_title: 'מצלמות',
    add_camera: '+ הוסף מצלמה',
    no_cameras: 'אין מצלמות',
    no_cameras_hint: 'הוסף מכשיר מסוג "מצלמה" בדף המכשירים, או לחץ + הוסף מצלמה',
    camera_stream_url: 'כתובת שידור',
    camera_stream_placeholder: 'http://192.168.1.x/video.mjpg',
    camera_snapshot_url: 'כתובת תמונה (אופציונלי)',
    camera_name: 'שם מצלמה',
    camera_refresh: 'רענן',
    camera_fullscreen: 'מסך מלא',
    camera_live: '● חי',
    camera_stream_type: 'סוג שידור',
    camera_type_mjpeg: 'MJPEG שידור',
    camera_type_snapshot: 'תמונת מצב (רענון אוטומטי)',
    camera_type_hls: 'HLS / MP4',
    camera_type_iframe: 'הטמעת אינטרנט',
    camera_edit_title: 'עריכת מצלמה',
    camera_add_title: 'הוסף מצלמה',
    sponsored: 'פינת פרסום',
    show_ads: '📢 הצג פרסומות',
    gemini_section_title: 'Gemini AI — עוזר בית חכם',
    gemini_hint: 'Gemini מאפשר שיחה קולית / כתובה לשליטה בבית: "כבה את אורות הסלון", "הגדר מזגן על 22°"',
    gemini_api_hint: 'קבל מפתח API בחינם ב-aistudio.google.com → Get API Key',
    gemini_after_save: 'לאחר שמירה — עבור למכשירים → + הוסף → ❄️ הוסף מזגן → יבא מ-Sensibo',
    sensibo_section_title: 'Sensibo — מזגנים חכמים',
    sensibo_hint: 'Sensibo מחבר כל מזגן (תדיראן, אלקטרה, גנרל, LG…) לרשת. קבל מפתח API ב-home.sensibo.com',
    qr_scanning: 'סורק... כוון למצלמה אל קוד QR',
    qr_not_available: 'מצלמה לא זמינה בדפדפן',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'חיבור לשרת הביתי',
    prev_url_warning: 'לא ניתן להתחבר ל:',
    phone_ip_hint: 'כתובת הטלפון:',
    phone_subnet_hint: '— ה-Hub צריך להיות על',
    discover_auto: '🔍 חפש Hub אוטומטית',
    enter_ip_manual: '✏️ הזן כתובת IP ידנית',
    hub_not_found_title: 'Hub לא נמצא — בדוק את הדברים הבאים:',
    hub_searching: 'מחפש Hub ברשת...', hub_found: '✅ Hub נמצא!',
    stop: 'עצור',
    hub_ip_label: 'הזן כתובת Hub',
    hub_ip_desc: 'הכתובת מופיעה בחלון start-hub.bat:',
    connect_btn2: '🔗 התחבר',
    cannot_connect_error: 'לא ניתן להתחבר ל',
    check_hub_running: 'ודא שהHub פועל (start-hub.bat כמנהל) ושהכתובת נכונה.',
    instructions_title: '📋 הוראות הפעלה',
    instr1: 'פתח תיקיית smarthome-hub\\hub במחשב',
    instr2: 'לחץ ימין על start-hub.bat ← הפעל כמנהל',
    instr3: 'ודא מחשב + טלפון על אותה רשת WiFi',
    instr4: 'לחץ "חפש Hub אוטומטית" ↑',
    checklist_bat: 'start-hub.bat פועל כמנהל?',
    checklist_bat_detail: 'לחץ ימין על start-hub.bat ← "הפעל כמנהל מערכת" (Run as Administrator). חלון שחור אמור להישאר פתוח עם הכתובת.',
    checklist_wifi: 'מחשב + טלפון על אותה רשת WiFi?',
    checklist_wifi_detail: 'ודא ששניהם מחוברים לאותו ראוטר. שמות הרשת (SSID) צריכים להיות זהים, או לפחות על אותה רשת ביתית.',
    checklist_firewall: 'חומת אש Windows חוסמת?',
    checklist_firewall_detail: 'כאשר Python הופעל בפעם הראשונה, אולי לחצת "חסום". פתח:\nחיפוש Windows → "Windows Defender Firewall" → "אפשר אפליקציה" → חפש Python → סמן הכל ← אשר.',
    checklist_isolation: 'AP Isolation מופעל בראוטר?',
    checklist_isolation_detail: 'כנס לממשק הראוטר (192.168.1.1)\nחפש: Wireless Settings → AP Isolation → כבה',
    checklist_ethernet: 'נסה חיבור Ethernet?',
    checklist_ethernet_detail: 'חבר את המחשב ישירות לראוטר בכבל רשת.',

    /* ── סוגי מכשירים ── */
    dev_type_switch: 'מתג/שקע', dev_type_light: 'נורה',
    dev_type_dimmer: 'דימר',    dev_type_sensor: 'חיישן',
    dev_type_fan: 'מאוורר',     dev_type_lock: 'מנעול',
    dev_type_camera: 'מצלמה',   dev_type_ac: 'מזגן',
    unknown_type: 'לא ידוע',

    /* ── רשת / סריקת מכשירים ── */
    net_scan_btn: '🔍 סרוק מכשירים ברשת',
    net_identifying: 'מזהה מכשירים...',
    net_hint_arp: 'בודק טבלת ARP...',
    net_hint_ping: 'שולח ping לרשת (עשוי לקחת עד 25 שניות)...',
    net_hint_tasmota: 'מחפש מכשירי Tasmota / Shelly...',
    net_hint_upnp: 'סורק UPnP / mDNS...',
    net_hint_almost: 'כמעט סיים...',
    net_no_devices_found: 'לא נמצאו מכשירים ברשת. ודא שאתה על אותה רשת WiFi.',
    net_scan_failed: 'סריקה נכשלה — ודא שה-Hub פועל',
    net_info_title: '🌐 מידע רשת מיידי',
    net_hub_ip: 'כתובת Hub', net_gateway: 'שער ברירת מחדל',
    net_subnet: 'רשת', net_arp_count: 'מכשירים ב-ARP',
    net_found: 'נמצאו', net_devices_word: 'מכשירים',
    net_auto_pairable: 'ניתנים לצימוד אוטומטי',
    net_auto_pair: '⚡ צימוד אוטומטי',
    net_manual_add_section: '🔧 הוספה ידנית',
    net_paired_section: '✅ מצומדים',
    net_mqtt_auto: '⚡ הגדרות MQTT יוגדרו אוטומטית על המכשיר',
    net_room_area: 'חדר / אזור',
    net_pairing: 'מצמד...',
    net_pair_auto_btn: '⚡ צמד אוטומטית',
    net_add_device_btn: '+ הוסף מכשיר',
    net_paired_tag: '✓ מצומד',
    net_auto_tag: '⚡ אוטו',
    net_pair_btn: '⚡ צמד',
    net_pair_error: 'שגיאה בצימוד',
    net_paired_ok: 'צומד ונוסף למערכת',
    net_tab_wifi: '📶 רשת',

    /* ── Bluetooth ── */
    bt_not_available: 'Bluetooth אינו זמין בדפדפן',
    bt_install_apk: 'התקן את ה-APK על מכשיר Android לשימוש בסריקת Bluetooth',
    bt_initializing: '⏳ מאתחל...',
    bt_stop_scan: '⏹ עצור סריקה',
    bt_scan_btn: '🔵 סרוק מכשירי Bluetooth',
    bt_scanning: 'מחפש מכשירי BLE בסביבה...',
    bt_empty_hint: 'לחץ סרוק כדי לחפש מכשירי Bluetooth בסביבה',
    bt_added_tag: '✓ נוסף',
    bt_add_to_system: '+ הוסף למערכת',
    bt_scan_error: 'סריקה נכשלה:',
    bt_save_error: 'שגיאה בשמירה',
    bt_added_ok: 'נוסף למערכת',

    /* ── Zigbee ── */
    z2m_active_label: 'Zigbee2MQTT ● פעיל (MQTT)',
    z2m_devices_connected: 'מכשירים מחוברים',
    z2m_scan_btn: '🔶 חפש גשרי Zigbee ברשת',
    z2m_no_bridges: 'לא נמצאו גשרי Zigbee ברשת. ודא שהמכשיר מחובר לאותה רשת.',
    z2m_found_bridges_word: 'גשרים',
    z2m_verified: '✓ מאומת', z2m_unverified: '❓ לא מאומת',
    z2m_devices_btn: '📋 מכשירים',
    z2m_loading_devices: '⏳ טוען מכשירים...',
    z2m_load_error: 'שגיאה בטעינת מכשירים',
    z2m_no_devices_hint: 'אין מכשירים זמינים — ודא ש-Zigbee2MQTT פועל ומחובר ל-MQTT',
    z2m_imported_tag: '✓ יובא',
    z2m_unsupported: 'לא נתמך',
    z2m_not_completed: '❓ לא הושלם',
    z2m_import_btn: '+ ייבא',
    z2m_mqtt_section: 'מכשירים מ-MQTT',
    z2m_load_btn: '📥 טען מכשירים מ-Zigbee2MQTT',
    z2m_import_error: 'שגיאה בייבוא',
    z2m_imported_ok: 'יובא בהצלחה',
    z2m_importing: '⏳ מייבא...',
    z2m_import_to_system: '+ ייבא למערכת',

    /* ── Matter ── */
    matter_active: '● פעיל', matter_inactive: '○ לא פעיל',
    matter_nodes_count: 'מכשירים מצומדים',
    matter_server_required: 'python-matter-server נדרש לצימוד',
    how_btn: '❓ איך?',
    matter_scan_btn: '🔍 סרוק מכשירי Matter',
    matter_commission_btn: '🔷 צמד מכשיר',
    matter_no_devices: 'לא נמצאו מכשירי Matter. ודא שהמכשיר בזיווג (pairing mode).',
    matter_ready_to_pair: '📲 מוכנים לצימוד',
    matter_already_paired: '✅ כבר מצומדים',
    matter_pair_btn: '🔗 צמד',
    matter_system_nodes: '🔷 מכשירי Matter במערכת',
    matter_modal_title: '🔷 צמד מכשיר Matter',
    matter_code_label: 'קוד צימוד (QR / מספר 11 ספרות)',
    matter_commissioning: '⏳ מצמד...',
    matter_enter_code: 'הכנס קוד צימוד',
    matter_pair_failed: 'צימוד נכשל',
    matter_remove_confirm_prefix: 'להסיר את',
    matter_remove_error: 'שגיאה בהסרה',
    matter_paired_ok: 'צומד בהצלחה',
    matter_scanning: '⏳ סורק...',

    /* ── WiFi ── */
    wifi_hub_connected_label: 'Hub מחובר · עוצמה',
    wifi_adapter_off: 'מתאם ה-WiFi כבוי או לא זמין במחשב',
    wifi_scan_btn: '📡 סרוק רשתות WiFi',
    wifi_scanning_label: 'סורק רשתות WiFi...',
    wifi_retrying: 'לא נמצאו רשתות — מנסה שוב...',
    wifi_last_scan: 'עדכון אחרון:',
    wifi_networks_count: 'רשתות',
    wifi_manual_hint: 'לא נמצאו רשתות — הזן שם ידנית:',
    wifi_ssid_placeholder: 'שם הרשת (SSID)...',
    wifi_dual_band: '📶 Dual-Band זוהה',
    wifi_iot_24ghz: '— מכשירי IoT (Tasmota/Shelly) תומכים רק ב-2.4GHz.',
    wifi_available_networks: '📡 רשתות זמינות',
    wifi_24ghz_label: '✓ 2.4 GHz — מתאים לבית חכם',
    wifi_5ghz_label: '⚡ 5 GHz — מהיר יותר (לא לIoT)',
    wifi_saved_routers_label: '💾 ראוטרים שמורים',
    wifi_priority_tag: '★ עדיפון',
    wifi_available_now: 'זמין',
    wifi_not_in_scan: 'לא נמצא בסריקה',
    wifi_secured: '🔒 מאובטח',
    wifi_open: 'פתוח',
    wifi_5ghz_warning: '⚠️ 5GHz — לא מתאים למכשירי IoT (Tasmota, Shelly).',
    wifi_password_label: 'סיסמת WiFi',
    wifi_save_next: 'שמור לפעמים הבאות',
    wifi_auto_on_start: 'חיבור אוטומטי בהפעלה',
    wifi_connecting_btn: '⏳ מתחבר...',
    wifi_connect_btn_label: '🔗 התחבר',
    wifi_enter_password: 'הכנס סיסמה',
    wifi_connected_ok: 'מחובר בהצלחה ל',
    wifi_conn_failed: 'חיבור נכשל — בדוק סיסמה',
    wifi_remove_confirm: 'מהרשתות השמורות?',
    wifi_saved_tag: '💾 שמור',
    wifi_open_badge: '🔓 פתוח',
  },

  /* ═══════════════════════════════ ARABIC ════════════════════════════════ */
  ar: {
    home: 'الرئيسية', devices: 'الأجهزة', automations: 'تلقائي',
    security: 'الأمان', rooms: 'الغرف', network: 'الشبكة',
    history: 'السجل', settings: 'الإعدادات',
    save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل',
    add: 'إضافة', close: 'إغلاق', search: 'بحث', loading: 'جارٍ التحميل...',
    save_changes: 'حفظ التغييرات', yes: 'نعم', no: 'لا', back: 'رجوع',
    error: 'خطأ', no_results: 'لا توجد نتائج', all: 'الكل',
    connected: 'متصل', connecting: 'جارٍ الاتصال...', disconnected: 'غير متصل',
    online: 'متصل', offline: 'غير متصل', active: 'نشط', inactive: 'غير نشط',
    devices_count: 'الأجهزة', connected_count: 'متصل',
    rooms_count: 'الغرف', automations_count: 'أتمتة',
    pinned_devices: '📌 مثبت', active_now: '⚡ نشط الآن',
    turn_all_off: 'إيقاف الكل', no_active_devices: 'لا توجد أجهزة نشطة',
    go_to_devices: 'إلى الأجهزة',
    recent_activity: 'النشاط الأخير', see_all: 'الكل ›',
    turned_on: 'تم التشغيل', turned_off: 'تم الإيقاف', command_sent: 'أمر',
    hub_not_connected: 'Hub غير متصل',
    hub_settings: '⚙️ إعدادات Hub', network_diag: '🔧 تشخيص الشبكة',
    recommended_products: '🛒 منتجات المنزل الذكي الموصى بها',
    show_recommendations: '🛒 عرض التوصيات',
    show_all: 'عرض الكل', show_less: 'عرض أقل', buy_now: 'اشترِ الآن ›',
    history_title: 'السجل', clear: 'مسح',
    no_history: 'لا توجد سجلات', search_history: '🔍 ابحث...',
    rooms_title: 'الغرف', new_room: '+ غرفة جديدة',
    no_rooms: 'لا توجد غرف', saving: 'جارٍ الحفظ...', no_room: 'بدون غرفة',
    security_title: 'الأمان', alarm_system: 'حالة الإنذار',
    disarmed: 'معطّل', home_mode: 'في المنزل', armed: 'مفعّل', night_mode: 'الليل',
    arming_in: 'سيفعّل بعد', seconds_abbr: 'ث',
    cancel_arm: 'إلغاء', active_alerts: 'تنبيهات نشطة',
    security_devices: 'أجهزة الأمان', connected_devices: 'متصل', alerts_count: 'تنبيهات',
    locks_section: 'الأقفال', motion_sensors: 'حساسات الحركة',
    door_sensors: 'حساسات الباب / النافذة', smoke_detectors: 'كاشفات الدخان',
    cameras_section: 'الكاميرات',
    security_history_title: 'أحداث الأمان الأخيرة',
    no_security_devices: 'لا توجد أجهزة أمان',
    no_recent_events: 'لا توجد أحداث أمان حديثة',
    lock_btn: 'قفل', unlock_btn: 'فتح',
    motion_detected_badge: '👤 تم الكشف', quiet_badge: '○ هادئ',
    door_open_badge: '🚪 مفتوح', door_closed_badge: '✅ مغلق',
    smoke_alert_badge: '🔥 دخان!', smoke_ok_badge: '✅ سليم',
    smoke_alert_banner: '🔥 تم اكتشاف دخان!',
    motion_alert_banner: '👤 تم اكتشاف حركة',
    door_open_banner: '🚪 مفتوح', offline_badge: '● غير متصل',
    view_stream: '▶ عرض البث',
    add_device: 'إضافة جهاز', no_devices: 'لا توجد أجهزة',
    pinned_section: '📌 مثبت', all_devices_section: 'جميع الأجهزة',
    brightness: 'السطوع', battery: 'البطارية',
    network_title: 'الشبكة والاتصالات', scanning: 'جارٍ المسح...',
    no_networks: 'لا توجد شبكات', connect_btn: 'اتصال',
    rules_title: 'الأتمتة', add_rule: '+ جديد', no_rules: 'لا توجد أتمتة',
    language: 'اللغة', about: 'حول', version: 'الإصدار',
    import_export: 'استيراد / تصدير', export_devices: 'تصدير الأجهزة',
    import_devices: 'استيراد الأجهزة',
    scenes_title: 'المشاهد', new_scene: '+ مشهد جديد',
    no_scenes: 'لا توجد مشاهد',
    no_scenes_hint: 'أنشئ مشهداً للتحكم في أجهزة متعددة بنقرة واحدة',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'غير مُهيأ — أضف مفتاح API في الإعدادات',
    type_message: 'اسألني شيئاً...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'الاتصال بالخادم المنزلي',
    discover_auto: '🔍 البحث التلقائي عن Hub',
    enter_ip_manual: '✏️ إدخال IP يدوياً',
    hub_searching: 'جارٍ البحث عن Hub...', hub_found: '✅ تم العثور على Hub!',
    stop: 'إيقاف', connect_btn2: '🔗 اتصال',
  },

  /* ══════════════════════════════ RUSSIAN ═════════════════════════════════ */
  ru: {
    home: 'Главная', devices: 'Устройства', automations: 'Авто',
    security: 'Охрана', rooms: 'Комнаты', network: 'Сеть',
    history: 'История', settings: 'Настройки',
    save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить',
    add: 'Добавить', close: 'Закрыть', search: 'Поиск', loading: 'Загрузка...',
    save_changes: 'Сохранить', yes: 'Да', no: 'Нет', back: 'Назад',
    error: 'Ошибка', no_results: 'Ничего не найдено', all: 'Все',
    connected: 'Подключён', connecting: 'Подключение...', disconnected: 'Отключён',
    online: 'Онлайн', offline: 'Офлайн', active: 'Активен', inactive: 'Неактивен',
    devices_count: 'Устройства', connected_count: 'Онлайн',
    rooms_count: 'Комнаты', automations_count: 'Автоматизации',
    pinned_devices: '📌 Закреплённые', active_now: '⚡ Активны',
    turn_all_off: 'Выключить всё', no_active_devices: 'Нет активных устройств',
    go_to_devices: 'К устройствам',
    recent_activity: 'Последние события', see_all: 'Все ›',
    turned_on: 'Включено', turned_off: 'Выключено', command_sent: 'Команда',
    hub_not_connected: 'Hub не подключён',
    hub_settings: '⚙️ Настройки Hub', network_diag: '🔧 Диагностика',
    recommended_products: '🛒 Рекомендуемые товары',
    show_recommendations: '🛒 Показать рекомендации',
    show_all: 'Показать всё', show_less: 'Показать меньше', buy_now: 'Купить ›',
    history_title: 'История', clear: 'Очистить',
    no_history: 'Нет записей', search_history: '🔍 Поиск...',
    rooms_title: 'Комнаты', new_room: '+ Новая комната',
    no_rooms: 'Нет комнат', saving: 'Сохранение...', no_room: 'Без комнаты',
    security_title: 'Охрана', alarm_system: 'Состояние охраны',
    disarmed: 'Снято', home_mode: 'Дома', armed: 'Охрана', night_mode: 'Ночь',
    arming_in: 'Включится через', seconds_abbr: 'с',
    cancel_arm: 'Отмена', active_alerts: 'Активные тревоги',
    security_devices: 'Устройства охраны', connected_devices: 'Онлайн',
    alerts_count: 'Тревоги',
    locks_section: 'Замки', motion_sensors: 'Датчики движения',
    door_sensors: 'Датчики двери/окна', smoke_detectors: 'Датчики дыма',
    cameras_section: 'Камеры',
    security_history_title: 'Последние события охраны',
    no_security_devices: 'Нет устройств охраны',
    no_recent_events: 'Нет недавних событий',
    lock_btn: 'Закрыть', unlock_btn: 'Открыть',
    motion_detected_badge: '👤 Движение', quiet_badge: '○ Тихо',
    door_open_badge: '🚪 Открыто', door_closed_badge: '✅ Закрыто',
    smoke_alert_badge: '🔥 Дым!', smoke_ok_badge: '✅ Норма',
    smoke_alert_banner: '🔥 Обнаружен дым!',
    motion_alert_banner: '👤 Обнаружено движение',
    door_open_banner: '🚪 Открыто', offline_badge: '● Офлайн',
    view_stream: '▶ Смотреть трансляцию',
    add_device: 'Добавить устройство', no_devices: 'Нет устройств',
    pinned_section: '📌 Закреплённые', all_devices_section: 'Все устройства',
    brightness: 'Яркость', battery: 'Батарея',
    network_title: 'Сеть и подключения', scanning: 'Сканирование...',
    no_networks: 'Сети не найдены', connect_btn: 'Подключить',
    rules_title: 'Автоматизации', add_rule: '+ Новая', no_rules: 'Нет автоматизаций',
    language: 'Язык', about: 'О приложении', version: 'Версия',
    import_export: 'Импорт / Экспорт', export_devices: 'Экспорт устройств',
    import_devices: 'Импорт устройств',
    scenes_title: 'Сцены', new_scene: '+ Новая сцена',
    no_scenes: 'Нет сцен',
    no_scenes_hint: 'Создайте сцену для управления несколькими устройствами одним нажатием',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'Не настроен — добавьте API-ключ в настройках',
    type_message: 'Спросите меня...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'Подключение к домашнему серверу',
    discover_auto: '🔍 Найти Hub автоматически',
    enter_ip_manual: '✏️ Ввести IP вручную',
    hub_searching: 'Поиск Hub в сети...', hub_found: '✅ Hub найден!',
    stop: 'Стоп', connect_btn2: '🔗 Подключить',
  },

  /* ══════════════════════════════ SPANISH ═════════════════════════════════ */
  es: {
    home: 'Inicio', devices: 'Dispositivos', automations: 'Auto',
    security: 'Seguridad', rooms: 'Habitaciones', network: 'Red',
    history: 'Historial', settings: 'Ajustes',
    save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar',
    add: 'Agregar', close: 'Cerrar', search: 'Buscar', loading: 'Cargando...',
    save_changes: 'Guardar cambios', yes: 'Sí', no: 'No', back: 'Volver',
    error: 'Error', no_results: 'Sin resultados', all: 'Todo',
    connected: 'Conectado', connecting: 'Conectando...', disconnected: 'Desconectado',
    online: 'En línea', offline: 'Sin conexión', active: 'Activo', inactive: 'Inactivo',
    devices_count: 'Dispositivos', connected_count: 'En línea',
    rooms_count: 'Hab.', automations_count: 'Automaciones',
    pinned_devices: '📌 Fijados', active_now: '⚡ Activos',
    turn_all_off: 'Apagar todo', no_active_devices: 'Sin dispositivos activos',
    go_to_devices: 'Ver dispositivos',
    recent_activity: 'Actividad reciente', see_all: 'Ver todo ›',
    turned_on: 'Encendido', turned_off: 'Apagado', command_sent: 'Comando',
    hub_not_connected: 'Hub desconectado',
    hub_settings: '⚙️ Ajustes Hub', network_diag: '🔧 Diagnóstico',
    recommended_products: '🛒 Productos recomendados',
    show_recommendations: '🛒 Mostrar recomendaciones',
    show_all: 'Ver todo', show_less: 'Ver menos', buy_now: 'Comprar ›',
    history_title: 'Historial', clear: 'Limpiar',
    no_history: 'Sin registros', search_history: '🔍 Buscar...',
    rooms_title: 'Habitaciones', new_room: '+ Nueva habitación',
    no_rooms: 'Sin habitaciones', saving: 'Guardando...', no_room: 'Sin habitación',
    security_title: 'Seguridad', alarm_system: 'Estado de alarma',
    disarmed: 'Desactivado', home_mode: 'En casa', armed: 'Armado', night_mode: 'Noche',
    arming_in: 'Se activa en', seconds_abbr: 's',
    cancel_arm: 'Cancelar', active_alerts: 'Alertas activas',
    security_devices: 'Disp. de seguridad', connected_devices: 'En línea',
    alerts_count: 'Alertas',
    locks_section: 'Cerraduras', motion_sensors: 'Sensores de movimiento',
    door_sensors: 'Sensores puerta/ventana', smoke_detectors: 'Detectores de humo',
    cameras_section: 'Cámaras',
    security_history_title: 'Eventos de seguridad recientes',
    no_security_devices: 'Sin dispositivos de seguridad',
    no_recent_events: 'Sin eventos recientes',
    lock_btn: 'Cerrar', unlock_btn: 'Abrir',
    motion_detected_badge: '👤 Detectado', quiet_badge: '○ Tranquilo',
    door_open_badge: '🚪 Abierto', door_closed_badge: '✅ Cerrado',
    smoke_alert_badge: '🔥 Humo!', smoke_ok_badge: '✅ OK',
    smoke_alert_banner: '🔥 ¡Humo detectado!',
    motion_alert_banner: '👤 Movimiento detectado',
    door_open_banner: '🚪 Abierto', offline_badge: '● Sin conexión',
    view_stream: '▶ Ver transmisión',
    add_device: 'Agregar dispositivo', no_devices: 'Sin dispositivos',
    pinned_section: '📌 Fijados', all_devices_section: 'Todos los dispositivos',
    brightness: 'Brillo', battery: 'Batería',
    network_title: 'Red y conexiones', scanning: 'Escaneando...',
    no_networks: 'Sin redes', connect_btn: 'Conectar',
    rules_title: 'Automaciones', add_rule: '+ Nueva', no_rules: 'Sin automaciones',
    language: 'Idioma', about: 'Acerca de', version: 'Versión',
    import_export: 'Importar / Exportar', export_devices: 'Exportar dispositivos',
    import_devices: 'Importar dispositivos',
    scenes_title: 'Escenas', new_scene: '+ Nueva escena',
    no_scenes: 'Sin escenas',
    no_scenes_hint: 'Crea una escena para controlar varios dispositivos con un toque',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'No configurado — agrega API key en Ajustes',
    type_message: 'Pregúntame algo...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'Conectar al servidor doméstico',
    discover_auto: '🔍 Buscar Hub automáticamente',
    enter_ip_manual: '✏️ Ingresar IP manualmente',
    hub_searching: 'Buscando Hub...', hub_found: '✅ Hub encontrado!',
    stop: 'Detener', connect_btn2: '🔗 Conectar',
  },

  /* ══════════════════════════════ FRENCH ══════════════════════════════════ */
  fr: {
    home: 'Accueil', devices: 'Appareils', automations: 'Auto',
    security: 'Sécurité', rooms: 'Pièces', network: 'Réseau',
    history: 'Historique', settings: 'Paramètres',
    save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier',
    add: 'Ajouter', close: 'Fermer', search: 'Rechercher', loading: 'Chargement...',
    save_changes: 'Enregistrer', yes: 'Oui', no: 'Non', back: 'Retour',
    error: 'Erreur', no_results: 'Aucun résultat', all: 'Tout',
    connected: 'Connecté', connecting: 'Connexion...', disconnected: 'Déconnecté',
    online: 'En ligne', offline: 'Hors ligne', active: 'Actif', inactive: 'Inactif',
    devices_count: 'Appareils', connected_count: 'En ligne',
    rooms_count: 'Pièces', automations_count: 'Automations',
    pinned_devices: '📌 Épinglés', active_now: '⚡ Actifs',
    turn_all_off: 'Tout éteindre', no_active_devices: 'Aucun appareil actif',
    go_to_devices: 'Voir appareils',
    recent_activity: 'Activité récente', see_all: 'Tout ›',
    turned_on: 'Allumé', turned_off: 'Éteint', command_sent: 'Commande',
    hub_not_connected: 'Hub déconnecté',
    hub_settings: '⚙️ Paramètres Hub', network_diag: '🔧 Diagnostic',
    recommended_products: '🛒 Produits recommandés',
    show_recommendations: '🛒 Voir recommandations',
    show_all: 'Tout voir', show_less: 'Voir moins', buy_now: 'Acheter ›',
    history_title: 'Historique', clear: 'Effacer',
    no_history: 'Aucun enregistrement', search_history: '🔍 Rechercher...',
    rooms_title: 'Pièces', new_room: '+ Nouvelle pièce',
    no_rooms: 'Aucune pièce', saving: 'Enregistrement...', no_room: 'Sans pièce',
    security_title: 'Sécurité', alarm_system: 'État de l\'alarme',
    disarmed: 'Désarmé', home_mode: 'À la maison', armed: 'Armé', night_mode: 'Nuit',
    arming_in: 'Armement dans', seconds_abbr: 's',
    cancel_arm: 'Annuler', active_alerts: 'Alertes actives',
    security_devices: 'Disp. sécurité', connected_devices: 'En ligne',
    alerts_count: 'Alertes',
    locks_section: 'Serrures', motion_sensors: 'Détecteurs de mouvement',
    door_sensors: 'Détecteurs porte/fenêtre', smoke_detectors: 'Détecteurs de fumée',
    cameras_section: 'Caméras',
    security_history_title: 'Événements sécurité récents',
    no_security_devices: 'Aucun appareil de sécurité',
    no_recent_events: 'Aucun événement récent',
    lock_btn: 'Verrouiller', unlock_btn: 'Déverrouiller',
    motion_detected_badge: '👤 Détecté', quiet_badge: '○ Calme',
    door_open_badge: '🚪 Ouvert', door_closed_badge: '✅ Fermé',
    smoke_alert_badge: '🔥 Fumée!', smoke_ok_badge: '✅ OK',
    smoke_alert_banner: '🔥 Fumée détectée!',
    motion_alert_banner: '👤 Mouvement détecté',
    door_open_banner: '🚪 Ouvert', offline_badge: '● Hors ligne',
    view_stream: '▶ Voir flux',
    add_device: 'Ajouter un appareil', no_devices: 'Aucun appareil',
    pinned_section: '📌 Épinglés', all_devices_section: 'Tous les appareils',
    brightness: 'Luminosité', battery: 'Batterie',
    network_title: 'Réseau et connexions', scanning: 'Scan...',
    no_networks: 'Aucun réseau', connect_btn: 'Connecter',
    rules_title: 'Automations', add_rule: '+ Nouvelle', no_rules: 'Aucune automation',
    language: 'Langue', about: 'À propos', version: 'Version',
    import_export: 'Import / Export', export_devices: 'Exporter appareils',
    import_devices: 'Importer appareils',
    scenes_title: 'Scènes', new_scene: '+ Nouvelle scène',
    no_scenes: 'Aucune scène',
    no_scenes_hint: 'Créez une scène pour contrôler plusieurs appareils d\'un seul geste',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'Non configuré — ajoutez la clé API dans Paramètres',
    type_message: 'Posez-moi une question...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'Connexion au serveur domestique',
    discover_auto: '🔍 Rechercher Hub automatiquement',
    enter_ip_manual: '✏️ Saisir IP manuellement',
    hub_searching: 'Recherche du Hub...', hub_found: '✅ Hub trouvé!',
    stop: 'Arrêter', connect_btn2: '🔗 Connecter',
  },

  /* ══════════════════════════════ GERMAN ══════════════════════════════════ */
  de: {
    home: 'Startseite', devices: 'Geräte', automations: 'Auto',
    security: 'Sicherheit', rooms: 'Zimmer', network: 'Netzwerk',
    history: 'Verlauf', settings: 'Einstellungen',
    save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten',
    add: 'Hinzufügen', close: 'Schließen', search: 'Suchen', loading: 'Laden...',
    save_changes: 'Änderungen speichern', yes: 'Ja', no: 'Nein', back: 'Zurück',
    error: 'Fehler', no_results: 'Keine Ergebnisse', all: 'Alle',
    connected: 'Verbunden', connecting: 'Verbinde...', disconnected: 'Getrennt',
    online: 'Online', offline: 'Offline', active: 'Aktiv', inactive: 'Inaktiv',
    devices_count: 'Geräte', connected_count: 'Online',
    rooms_count: 'Zimmer', automations_count: 'Automationen',
    pinned_devices: '📌 Angeheftet', active_now: '⚡ Aktiv',
    turn_all_off: 'Alles ausschalten', no_active_devices: 'Keine aktiven Geräte',
    go_to_devices: 'Zu Geräten',
    recent_activity: 'Letzte Aktivität', see_all: 'Alle ›',
    turned_on: 'Eingeschaltet', turned_off: 'Ausgeschaltet', command_sent: 'Befehl',
    hub_not_connected: 'Hub nicht verbunden',
    hub_settings: '⚙️ Hub-Einstellungen', network_diag: '🔧 Netzwerkdiagnose',
    recommended_products: '🛒 Empfohlene Produkte',
    show_recommendations: '🛒 Empfehlungen anzeigen',
    show_all: 'Alle anzeigen', show_less: 'Weniger anzeigen', buy_now: 'Kaufen ›',
    history_title: 'Verlauf', clear: 'Löschen',
    no_history: 'Keine Einträge', search_history: '🔍 Suchen...',
    rooms_title: 'Zimmer', new_room: '+ Neues Zimmer',
    no_rooms: 'Keine Zimmer', saving: 'Speichern...', no_room: 'Kein Zimmer',
    security_title: 'Sicherheit', alarm_system: 'Alarmzustand',
    disarmed: 'Deaktiviert', home_mode: 'Zuhause', armed: 'Aktiviert', night_mode: 'Nacht',
    arming_in: 'Aktivierung in', seconds_abbr: 's',
    cancel_arm: 'Abbrechen', active_alerts: 'Aktive Alarme',
    security_devices: 'Sicherheitsgeräte', connected_devices: 'Online',
    alerts_count: 'Alarme',
    locks_section: 'Schlösser', motion_sensors: 'Bewegungsmelder',
    door_sensors: 'Tür-/Fenstersensoren', smoke_detectors: 'Rauchmelder',
    cameras_section: 'Kameras',
    security_history_title: 'Letzte Sicherheitsereignisse',
    no_security_devices: 'Keine Sicherheitsgeräte',
    no_recent_events: 'Keine aktuellen Ereignisse',
    lock_btn: 'Sperren', unlock_btn: 'Entsperren',
    motion_detected_badge: '👤 Erkannt', quiet_badge: '○ Ruhig',
    door_open_badge: '🚪 Offen', door_closed_badge: '✅ Geschlossen',
    smoke_alert_badge: '🔥 Rauch!', smoke_ok_badge: '✅ OK',
    smoke_alert_banner: '🔥 Rauch erkannt!',
    motion_alert_banner: '👤 Bewegung erkannt',
    door_open_banner: '🚪 Offen', offline_badge: '● Offline',
    view_stream: '▶ Stream ansehen',
    add_device: 'Gerät hinzufügen', no_devices: 'Keine Geräte',
    pinned_section: '📌 Angeheftet', all_devices_section: 'Alle Geräte',
    brightness: 'Helligkeit', battery: 'Akku',
    network_title: 'Netzwerk & Verbindungen', scanning: 'Scannen...',
    no_networks: 'Keine Netzwerke', connect_btn: 'Verbinden',
    rules_title: 'Automationen', add_rule: '+ Neue', no_rules: 'Keine Automationen',
    language: 'Sprache', about: 'Über', version: 'Version',
    import_export: 'Import / Export', export_devices: 'Geräte exportieren',
    import_devices: 'Geräte importieren',
    scenes_title: 'Szenen', new_scene: '+ Neue Szene',
    no_scenes: 'Keine Szenen',
    no_scenes_hint: 'Erstellen Sie eine Szene, um mehrere Geräte mit einem Tippen zu steuern',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'Nicht konfiguriert — API-Schlüssel in Einstellungen hinzufügen',
    type_message: 'Fragen Sie mich...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'Mit dem Heimserver verbinden',
    discover_auto: '🔍 Hub automatisch finden',
    enter_ip_manual: '✏️ IP manuell eingeben',
    hub_searching: 'Hub wird gesucht...', hub_found: '✅ Hub gefunden!',
    stop: 'Stopp', connect_btn2: '🔗 Verbinden',
  },

  /* ══════════════════════════ PORTUGUESE ═════════════════════════════════ */
  pt: {
    home: 'Início', devices: 'Dispositivos', automations: 'Auto',
    security: 'Segurança', rooms: 'Cômodos', network: 'Rede',
    history: 'Histórico', settings: 'Configurações',
    save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar',
    add: 'Adicionar', close: 'Fechar', search: 'Buscar', loading: 'Carregando...',
    save_changes: 'Salvar alterações', yes: 'Sim', no: 'Não', back: 'Voltar',
    error: 'Erro', no_results: 'Sem resultados', all: 'Tudo',
    connected: 'Conectado', connecting: 'Conectando...', disconnected: 'Desconectado',
    online: 'Online', offline: 'Offline', active: 'Ativo', inactive: 'Inativo',
    devices_count: 'Dispositivos', connected_count: 'Online',
    rooms_count: 'Cômodos', automations_count: 'Automações',
    pinned_devices: '📌 Fixados', active_now: '⚡ Ativos',
    turn_all_off: 'Desligar tudo', no_active_devices: 'Sem dispositivos ativos',
    go_to_devices: 'Ver dispositivos',
    recent_activity: 'Atividade recente', see_all: 'Ver tudo ›',
    turned_on: 'Ligado', turned_off: 'Desligado', command_sent: 'Comando',
    hub_not_connected: 'Hub desconectado',
    hub_settings: '⚙️ Configurações Hub', network_diag: '🔧 Diagnóstico',
    recommended_products: '🛒 Produtos recomendados',
    show_recommendations: '🛒 Mostrar recomendações',
    show_all: 'Ver tudo', show_less: 'Ver menos', buy_now: 'Comprar ›',
    history_title: 'Histórico', clear: 'Limpar',
    no_history: 'Sem registros', search_history: '🔍 Buscar...',
    rooms_title: 'Cômodos', new_room: '+ Novo cômodo',
    no_rooms: 'Sem cômodos', saving: 'Salvando...', no_room: 'Sem cômodo',
    security_title: 'Segurança', alarm_system: 'Estado do alarme',
    disarmed: 'Desarmado', home_mode: 'Em casa', armed: 'Armado', night_mode: 'Noite',
    arming_in: 'Ativando em', seconds_abbr: 's',
    cancel_arm: 'Cancelar', active_alerts: 'Alertas ativos',
    security_devices: 'Disp. de segurança', connected_devices: 'Online',
    alerts_count: 'Alertas',
    locks_section: 'Fechaduras', motion_sensors: 'Sensores de movimento',
    door_sensors: 'Sensores porta/janela', smoke_detectors: 'Detectores de fumaça',
    cameras_section: 'Câmeras',
    security_history_title: 'Eventos de segurança recentes',
    no_security_devices: 'Sem dispositivos de segurança',
    no_recent_events: 'Sem eventos recentes',
    lock_btn: 'Trancar', unlock_btn: 'Destrancar',
    motion_detected_badge: '👤 Detectado', quiet_badge: '○ Tranquilo',
    door_open_badge: '🚪 Aberto', door_closed_badge: '✅ Fechado',
    smoke_alert_badge: '🔥 Fumaça!', smoke_ok_badge: '✅ OK',
    smoke_alert_banner: '🔥 Fumaça detectada!',
    motion_alert_banner: '👤 Movimento detectado',
    door_open_banner: '🚪 Aberto', offline_badge: '● Offline',
    view_stream: '▶ Ver transmissão',
    add_device: 'Adicionar dispositivo', no_devices: 'Sem dispositivos',
    pinned_section: '📌 Fixados', all_devices_section: 'Todos os dispositivos',
    brightness: 'Brilho', battery: 'Bateria',
    network_title: 'Rede e conexões', scanning: 'Escaneando...',
    no_networks: 'Sem redes', connect_btn: 'Conectar',
    rules_title: 'Automações', add_rule: '+ Nova', no_rules: 'Sem automações',
    language: 'Idioma', about: 'Sobre', version: 'Versão',
    import_export: 'Importar / Exportar', export_devices: 'Exportar dispositivos',
    import_devices: 'Importar dispositivos',
    scenes_title: 'Cenas', new_scene: '+ Nova cena',
    no_scenes: 'Sem cenas',
    no_scenes_hint: 'Crie uma cena para controlar vários dispositivos com um toque',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'Não configurado — adicione API key nas Configurações',
    type_message: 'Me pergunte algo...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'Conectar ao servidor doméstico',
    discover_auto: '🔍 Encontrar Hub automaticamente',
    enter_ip_manual: '✏️ Inserir IP manualmente',
    hub_searching: 'Procurando Hub...', hub_found: '✅ Hub encontrado!',
    stop: 'Parar', connect_btn2: '🔗 Conectar',
  },

  /* ══════════════════════════════ AMHARIC ═════════════════════════════════ */
  am: {
    home: 'ቤት', devices: 'መሳሪያዎች', automations: 'አውቶ',
    security: 'ደህንነት', rooms: 'ክፍሎች', network: 'ኔትወርክ',
    history: 'ታሪክ', settings: 'ቅንብሮች',
    save: 'አስቀምጥ', cancel: 'ሰርዝ', delete: 'ሰርዝ', edit: 'አርም',
    add: 'ጨምር', close: 'ዝጋ', search: 'ፈልግ', loading: 'በመጫን ላይ...',
    yes: 'አዎ', no: 'አይ', back: 'ተመለስ', error: 'ስህተት',
    connected: 'ተገናኝቷል', connecting: 'እየተገናኘ...', disconnected: 'ያልተገናኘ',
    online: 'ኦንላይን', offline: 'ኦፍላይን', active: 'ንቁ', inactive: 'ንቁ አይደለም',
    devices_count: 'መሳሪያዎች', connected_count: 'ተገናኝቷል',
    rooms_count: 'ክፍሎች', automations_count: 'አውቶሜሽን',
    pinned_devices: '📌 ተሰካ', active_now: '⚡ አሁን ንቁ',
    turn_all_off: 'ሁሉ አጥፋ', no_active_devices: 'ምንም ንቁ መሳሪያ የለም',
    go_to_devices: 'ወደ መሳሪያዎች',
    recent_activity: 'ቅርብ ጊዜ እንቅስቃሴ', see_all: 'ሁሉ ›',
    turned_on: 'ተበርቷል', turned_off: 'ጠፍቷል', command_sent: 'ትዕዛዝ',
    hub_not_connected: 'Hub አልተገናኘም',
    hub_settings: '⚙️ Hub ቅንብሮች', network_diag: '🔧 ምርመራ',
    recommended_products: '🛒 የሚመከሩ ምርቶች',
    show_recommendations: '🛒 ምክሮችን አሳይ',
    show_all: 'ሁሉ አሳይ', show_less: 'ያነሰ አሳይ', buy_now: 'ግዛ ›',
    history_title: 'ታሪክ', clear: 'አጽዳ',
    no_history: 'ምንም መዝገቦች የሉም', search_history: '🔍 ፈልግ...',
    rooms_title: 'ክፍሎች', new_room: '+ አዲስ ክፍል',
    no_rooms: 'ምንም ክፍሎች የሉም', saving: 'እየተቀመጠ...', no_room: 'ክፍል የለም',
    security_title: 'ደህንነት', alarm_system: 'የማስጠንቀቂያ ሁኔታ',
    disarmed: 'ጠፍቷል', home_mode: 'ቤት', armed: 'ንቁ', night_mode: 'ሌሊት',
    arming_in: 'ይነቃል በ', seconds_abbr: 'ሰ',
    cancel_arm: 'ሰርዝ', active_alerts: 'ንቁ ማስጠንቀቂያዎች',
    security_devices: 'የደህንነት መሳሪያዎች', connected_devices: 'ተገናኝቷል',
    alerts_count: 'ማስጠንቀቂያዎች',
    locks_section: 'መቆለፊያዎች', motion_sensors: 'እንቅስቃሴ ዳሳሾች',
    door_sensors: 'የደጅ ዳሳሾች', smoke_detectors: 'የጢስ ዳሳሾች',
    cameras_section: 'ካሜራዎች',
    security_history_title: 'የቅርብ ጊዜ የደህንነት ክስተቶች',
    no_security_devices: 'ምንም የደህንነት መሳሪያዎች የሉም',
    no_recent_events: 'ምንም ቅርብ ጊዜ ክስተቶች የሉም',
    lock_btn: 'ቆልፍ', unlock_btn: 'ክፈት',
    motion_detected_badge: '👤 ተገኝቷል', quiet_badge: '○ ጸጥ',
    door_open_badge: '🚪 ክፍት', door_closed_badge: '✅ ዝግ',
    smoke_alert_badge: '🔥 ጢስ!', smoke_ok_badge: '✅ ጥሩ',
    smoke_alert_banner: '🔥 ጢስ ተገኝቷል!',
    motion_alert_banner: '👤 እንቅስቃሴ ተገኝቷል',
    door_open_banner: '🚪 ክፍት', offline_badge: '● ኦፍላይን',
    view_stream: '▶ ቀጥታ ስርጭት',
    add_device: 'መሳሪያ ጨምር', no_devices: 'ምንም መሳሪያዎች የሉም',
    pinned_section: '📌 ተሰካ', all_devices_section: 'ሁሉም መሳሪያዎች',
    brightness: 'ብሩህነት', battery: 'ባትሪ',
    network_title: 'ኔትወርክ እና ግንኙነቶች', scanning: 'እየፈለገ...',
    no_networks: 'ምንም ኔትወርኮች', connect_btn: 'ተገናኝ',
    rules_title: 'አውቶሜሽን', add_rule: '+ አዲስ', no_rules: 'ምንም አውቶሜሽን',
    language: 'ቋንቋ', about: 'ስለ', version: 'ስሪት',
    import_export: 'ማስገባት / ወደ ውጭ መላክ',
    export_devices: 'መሳሪያዎችን ወደ ውጭ ላክ',
    import_devices: 'መሳሪያዎችን አስገባ',
    scenes_title: 'ትዕይንቶች', new_scene: '+ አዲስ ትዕይንት',
    no_scenes: 'ምንም ትዕይንቶች የሉም',
    no_scenes_hint: 'ብዙ መሳሪያዎችን በአንድ ጠቅ ለመቆጣጠር ትዕይንት ይፍጠሩ',
    ai_assistant: '✨ Gemini AI',
    ai_not_configured: 'አልተዋቀረም — API ቁልፍ በቅንብሮች ይጨምሩ',
    type_message: 'ይጠይቁኝ...',
    hub_setup_title: 'Fantatech Hub', hub_setup_subtitle: 'ወደ ቤት አገልጋይ ይገናኙ',
    discover_auto: '🔍 Hub ራሱ ይፈልጉ',
    enter_ip_manual: '✏️ IP ያስገቡ',
    hub_searching: 'Hub እየፈለገ...', hub_found: '✅ Hub ተገኝቷል!',
    stop: 'አቁም', connect_btn2: '🔗 ተገናኝ',
  },
}

/* ── Context ──────────────────────────────────────────────────────────────── */
const LangContext = createContext({ lang: 'he', t: T.en, setLang: () => {}, rtl: false, locale: 'he-IL' })

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem('fantatech_lang') || 'he'
  )
  const changeLang = (l) => {
    setLangState(l)
    localStorage.setItem('fantatech_lang', l)
  }
  /* merge: English base + chosen language overrides */
  const t      = { ...T.en, ...(T[lang] || {}) }
  const meta   = LANG_META[lang] ?? LANG_META.en
  const rtl    = meta.rtl
  const locale = meta.locale

  return (
    <LangContext.Provider value={{ lang, t, setLang: changeLang, rtl, locale }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
export default LangContext
